version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: gameswithfriends
      POSTGRES_PASSWORD: password
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./api-node
    env_file: ./api-node/.env
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "81:81"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
