version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gameswithfriends
      POSTGRES_PASSWORD: password
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./api-node
    env_file: ./api-node/.env
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  postgres:
