version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gameswithfriends
      POSTGRES_PASSWORD: password
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./api-node
    volumes:
      - ./api-node:/app
      - /app/node_modules
    env_file: ./api-node/.env
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "81:81"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  postgres:
